name: generate gif
on:
  push:
    paths-ignore: main.gif
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: $GITHUB_WORKFLOW
  cancel-in-progress: true
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: |
        cd emu2
        make
        sudo make install
        cd ..
        sudo apt-get update
        sudo apt-get install qrencode nasm ffmpeg python3-pip -y --no-install-recommends
        cargo install --git https://github.com/asciinema/agg
        cargo install --locked --git https://github.com/asciinema/asciinema
        pip3 install --upgrade cmake
        git clone https://github.com/OHF-Voice/piper1-gpl --depth 1
        cd piper1-gpl/libpiper
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install
        cmake --build build
        cmake --install build
        cd ../..
        mv piper1-gpl/libpiper/install/espeak-ng-data/ .
        sudo cp piper1-gpl/libpiper/install/libpiper.so /usr/lib/
        sudo cp piper1-gpl/libpiper/lib/onnxruntime*/lib/libonnxruntime.so.1 /usr/lib/
        wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx
        wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json
        g++ -std=c++17 main.cpp -o main -I piper1-gpl/libpiper/install/include/ -I piper1-gpl/libpiper/include/ -I piper1-gpl/libpiper/lib/onnxruntime*/include/ -L piper1-gpl/libpiper/install/ -L piper1-gpl/libpiper/install/lib/ -lutil -lpiper -lonnxruntime
        asciinema rec main.cast -c ./main -i 1000
        agg main.cast main.gif --cols 110 --rows 50 --theme monokai --no-loop
        ffmpeg -f s16le -ar $(cat fr.txt) -ac 1 -i main.raw -i main.gif -c:v libx264 -af apad -c:a aac -b:a 128k -crf 0 -y -shortest output.mp4 || true
        git add main.gif output.mp4
        git config --global user.email "$GITHUB_REPOSITORY_OWNER_ID+$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
        git config --global user.name "$GITHUB_REPOSITORY_OWNER"
        git commit -m "$GITHUB_WORKFLOW" || true
        git push || true
        
