name: generate gif
on:
  push:
    paths-ignore: main.gif
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: $GITHUB_WORKFLOW
  cancel-in-progress: true
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: |
        cd emu2
        make
        sudo make install
        cd ..
        sudo apt-get update
        sudo apt-get install qrencode nasm libespeak-ng-dev ffmpeg -y --no-install-recommends
        cargo install --git https://github.com/asciinema/agg
        cargo install --locked --git https://github.com/asciinema/asciinema
        gcc main.c -o main -lutil -lespeak-ng
        asciinema rec main.cast -c ./main -i 1000 --return
        agg main.cast main.gif --cols 110 --rows 50
        ffmpeg -f s16le -ar $(cat fr.txt) -ac 1 -i main.raw -i main.gif -c:v libx264 -c:a aac -b:a 128k -crf 0 -shortest -y output.mp4
        git add main.gif output.mp4
        git config --global user.email "$GITHUB_REPOSITORY_OWNER_ID+$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
        git config --global user.name "$GITHUB_REPOSITORY_OWNER"
        git commit -m "$GITHUB_WORKFLOW" || true
        git push || true
        
